apiVersion: harness.io/v1
kind: Workflow
name: Provision Java App
identifier: Provision_Java_App
type: workflow
owner: user:account/natalie.finnegan@harness.io
projectIdentifier: default_project
orgIdentifier: default
metadata:
  description: |
    Scaffolds a new Java Spring Boot app via Cookiecutter, creates a GitHub repo,
    optionally registers the component in IDP, builds & pushes an image, and deploys to Dev
    using the Java_App_Provisioner pipeline.
  actionButton:
    text: Provision
spec:
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
      - title: Catalog (if registered)
        url: ${{ steps.trigger.output['pipeline.stages.App_Provisioner.spec.execution.steps.Register_Component.output.outputVariables.CATALOG_URL'] }}
  parameters:
    - title: Application Details
      required:
        - project_name
        - project_owner
      properties:
        project_name:
          title: Application Name
          type: string
          description: Human-readable name (e.g., Java Parson One”).
          minLength: 3
          maxLength: 50
          pattern: ^[A-Za-z]+(?:[ _-][A-Za-z]+)*$
          ui:options:
            placeholder: Java Parson One
            help: Letters/spaces/dash/underscore; no leading/trailing spaces.
        project_owner:
          title: App Owner (email)
          type: string
          format: email
          default: todd.parson@harness.io
        project_description:
          title: App Description
          type: string
          default: A sample Java application built with Spring Boot
    - title: Options
      properties:
        testing:
          title: Dry run only?
          type: string
          enum:
            - "yes"
            - "no"
          default: "no"
        register_component:
          title: Automatically register in the IDP catalog
          type: boolean
          default: false
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Provision Java App
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/sPn9anBcT3-jpii6rWBlTg/all/orgs/default/projects/default_project/pipelines/Java_App_Provisioner/pipeline-studio/?storeType=INLINE
        apikey: ${{ parameters.token }}
        inputset:
          project_name: ${{ parameters.project_name }}
          project_description: ${{ parameters.project_description }}
          project_owner: ${{ parameters.project_owner }}
          group_id: ${{ parameters.group_id }}
          version: ${{ parameters.version }}
          testing: ${{ parameters.testing }}
          enforce_requestor_access: ${{ parameters.enforce_requestor_access }}
          gh_org: ${{ parameters.gh_org }}
          connector_ref: ${{ parameters.connector_ref }}
          k8s_namespace: ${{ parameters.k8s_namespace }}
          sonar_url: ${{ parameters.sonar_url }}
          register_component: ${{ parameters.register_component and "true" or "false" }}
        showOutputVariables: true
